parent(abraham,homer).
parent(mona,homer).
parent(clancy,marge).
parent(jackie,marge).
parent(jackie,selma).
parent(jackie,patty).
parent(homer,bart).
parent(homer,lisa).
parent(marge,bart).
parent(marge,lisa).
male(abraham).
male(homer).
male(jackie).
male(bart).
female(clancy).
female(marge).
female(selma).
female(patty).
female(lisa).
female(mona).
female(maggie).
female(selma).
female(ling).
